chore: update husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,12 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" -o "$branch" = "main" ]; then
+  echo "You can't commit directly to (master|main) branch"
+  exit 1
+fi
+
 npx lint-staged
 npm run test:staged
